connectedin/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('perfis.urls')),
    url(r'^', include('usuarios.urls'))
]

perfis/urls.py
from django.conf.urls import url
from perfis import views

urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^perfis/(?P<perfil_id>\d+)$', views.exibir, name='perfil'),
    url(r'^perfis/(?P<perfil_id>\d+)/convidar$', views.convidar, name='convite'),
    url(r'^convite/(?P<convite_id>\d+)/aceitar$', views.aceitar, name='aceitar_convite')
]

usuarios/urls.py
from django.conf.urls import url
from views import RegistrarUsuarioView
from django.contrib.auth.views import login, logout_then_login


urlpatterns = [
    url(r'^registrar/$', RegistrarUsuarioView.as_view(), name='registrar'),
    url(r'^login/$', login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/$', logout_then_login, {'login_url':'/login/'}, name='logout')
]

perfis/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User


class Perfil(models.Model):

    nome = models.CharField(max_length=255, null=False)
    telefone = models.CharField(max_length=32, null=False)
    nome_da_empresa = models.CharField(max_length=255, null=False)
    contatos = models.ManyToManyField('self')
    usuario = models.OneToOneField(User, related_name="perfil")

    @property
    def email(self):
        return self.usuario.email

    def convidar(self, perfil_convidado):
        convite = Convite(solicitante=self, convidado=perfil_convidado)
        convite.save()


class Convite(models.Model):
    solicitante = models.ForeignKey(Perfil, related_name='convites_feitos')
    convidado = models.ForeignKey(Perfil, related_name='convites_recebidos')

    def aceitar(self):
        self.convidado.contatos.add(self.solicitante)
        self.solicitante.contatos.add(self.convidado)
        self.delete()

usuarios/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User


class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=False)
    nome_empresa = forms.CharField(required=False)

    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adicionar_erro('Por favor, verifique os dados informados')
            valid = False

        usuario_existente = User.objects.filter(username=self.data['nome']).exists()
        if usuario_existente:
            self.adicionar_erro('Usuario ja cadastrado')
            valid = False

        return valid

    def adicionar_erro(self, mensagem):
        erros = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        erros.append(mensagem)

perfis/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from perfis.models import Perfil, Convite


@login_required
def index(request):
    perfis = Perfil.objects.all()
    perfil_logado = get_perfil_logado(request)
    return render(request, 'index.html', {"perfis": perfis, "perfil_logado": perfil_logado})


@login_required
def exibir(request, perfil_id):
    perfil = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)
    ja_eh_contato = perfil in perfil_logado.contatos.all()

    return render(request, 'perfil.html', {"perfil": perfil, "ja_eh_contato": ja_eh_contato})


@login_required
def convidar(request, perfil_id):
    perfil_convidado = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)
    perfil_logado.convidar(perfil_convidado=perfil_convidado)
    return redirect('home')


@login_required
def get_perfil_logado(request):
    return request.user.perfil


@login_required
def aceitar(request, convite_id):
    convite = Convite.objects.get(id=convite_id)
    convite.aceitar()
    return redirect('home')

usuarios/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.contrib.auth.models import User
from usuarios.forms import RegistrarUsuarioForm
from perfis.models import Perfil


class RegistrarUsuarioView(View):

    template_name = 'registrar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        form = RegistrarUsuarioForm(request.POST)
        if form.is_valid():
            dados_form = form.data

            usuario = User.objects.create_user(dados_form['nome'], dados_form['email'], dados_form['senha'])
            perfil = (Perfil(nome=dados_form['nome'],
                             telefone=dados_form['telefone'],
                             nome_da_empresa=dados_form['nome_da_empresa'],
                             usuario=usuario))
            perfil.save()
            return redirect('home')

        return render(request, self.template_name, {"form": form})

perfis/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>ConnectedIn</title>
    <link rel="stylesheet" href="{% static "styles/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "styles/main.css" %}">
</head>
<body>
    <div class="container">
        <div class="header">
            <ul class="nav nav-pills pull-right">
                <li><a href="{% url 'home' %}">{{ perfil_logado.nome }}</a></li>
                <li><a href="/logout">Sair</a></li>
            </ul>
            <h3 class="text-muted">ConnectedIn</h3>
        </div>
        <div class="row content">
            {% block body %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

perfis/templates/index.html
{% extends "base.html"  %}
{% block body %}
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>Todos os perfis</strong>
            </div>
            {% if perfis%}
                <ul>
                    {% for perfil in perfis %}
                        <li>
                            <a href="{% url 'perfil' perfil.id %}">{{ perfil.id }} - {{ perfil.nome }} / {{ perfil.email }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>Nenhum perfil encontrado</p>
            {% endif %}
        </div>

        <div class="panel panel-default">
            {% with total_de_convites=perfil_logado.convites_recebidos.count %}
                {% if total_de_convites %}
                    <div class="panel-heading">
                        <strong>Você tem {{ total_de_convites }} convite{{ total_de_convites | pluralize }} aguardando aprovação</strong>
                    </div>
                    <ul class="list-group">
                        {% for convite in perfil_logado.convites_recebidos.all %}
                            <li class="list-group-item">
                                {{ convite.solicitante.nome }}
                                <a href="{% url 'aceitar_convite' convite.id %}" class="pull-right">Aceitar</a>
                            </li>
                        {% endfor %}
                    </ul>
                {%  else %}
                    <div class="panel-body">
                    <p>Nenhum convite recebido :(</p>
                    </div>
                {% endif %}
            {% endwith %}
        </div>

        <div class="panel panel-default">
            {% with total_de_contatos=perfil_logado.contatos.count %}
                {% if total_de_contatos %}
                    <div class="panel-heading">
                        <strong>Você tem {{ total_de_contatos }} contato{{ total_de_contatos | pluralize }}</strong>
                    </div>
                    <ul class="list-group">
                        {% for contato in perfil_logado.contatos.all %}
                            <li class="list-group-item">
                                <a href="{% url 'perfil' contato.id %}">{{ contato.nome }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                {%  else %}
                    <div class="panel-body">
                    <p>Você não possui nenhum contato :(</p>
                    </div>
                {% endif %}
            {% endwith %}
        </div>

    </div>
{% endblock %}

perfis/templates/perfil.html
{% extends "base.html"  %}
{% block body %}
    <div class="row">
        <div class="col-lg-12">
            <h2 style="margin-top: 0">{{ perfil.nome }}</h2>

            <address>
                <strong>{{ perfil.nome_da_empresa }}</strong><br>
                <abbr title="Telefone">Tel:</abbr>{{ perfil.telefone }}
                <a href="mailto:{{ perfil.email }}">{{ perfil.email }}</a>
            </address>

            {% if ja_eh_contato %}
                <div class="well well-sm">
                Vocês estão conectados
                </div>
            {% else %}
                <a href="{% url 'convite' perfil.id %}">convidar</a>
            {% endif %}

        </div>
    </div>
{% endblock %}

usuarios/templates/base_usuario.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>ConnectedIn</title>
    <link rel="stylesheet" href="{% static "styles/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "styles/main.css" %}">
    <link rel="stylesheet" href="{% static "styles/signin.css" %}">
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

usuarios/templates/login.html
{% extends "base_usuario.html" %}
{% block body %}
    <form class="form-signin" role="form" action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading">Login</h2>
        <input type="text" id="username" name="username" class="form-control" placeholder="Nome" required autofocus>
        <input type="password" id="id_password" name="password" class="form-control" placeholder="senha" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>
        <input type="hidden" name="next" value="{{ next }}"/>
        {% if form.errors %}
            <div class="alert alert-danger">
                <button type="button" class="close">&times;</button>
                Verifique os dados informados
            </div>
        {% endif %}
        <a href="{% url 'registrar' %}">Cadastrar</a>
    </form>
{% endblock %}

usuarios/templates/registrar.html
{% extends "base_usuario.html" %}
{% block body %}
    <form class="form-signin" action="{% url 'registrar' %}" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading">Crie seu usuário</h2>

        <input id="id_email" name="email" type="text" class="form-control" placeholder="Email *" required>
        <input id="id_nome" name="nome" type="text" class="form-control" placeholder="Nome *" required>
        <input id="id_senha" name="senha" type="password" class="form-control" placeholder="Senha *" required>
        <input id="id_telefone" name="telefone" type="text" class="form-control" placeholder="Telefone">
        <input id="id_nome_empresa" name="nome_da_empresa" type="text" class="form-control" placeholder="Empresa">

        <hr/>

        {% if form.errors %}
            <div class="alert alert-danger">
                <button type="button" class="close">&times;</button>
                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Registrar</button>
    </form>
{%  endblock %}